export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_SUCCESS_USER = 'LOGIN_SUCCESS_USER';
export const LOGIN_ERROR_USER = 'LOGIN_ERROR_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_SUCCESS_USER = 'SIGNUP_SUCCESS_USER';
export const SIGNUP_ERROR_USER = 'SIGNUP_ERROR_USER';
export const LOGOUT_USER = 'LOGOUT_USER';
export const LOGOUT_SUCCESS_USER = 'LOGOUT_SUCCESS_USER';
export const LOGOUT_ERROR_USER = 'LOGOUT_ERROR_USER';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS_USER = 'REGISTER_SUCCESS_USER';
export const REGISTER_ERROR_USER = 'REGISTER_ERROR_USER';
export const CHANGE_USER_LANG = 'CHANGE_USER_LANG';
export const CHANGE_USER_LANG_SUCCESS = 'CHANGE_USER_LANG_SUCCESS';
export const CHANGE_USER_LANG_ERROR = 'CHANGE_USER_LANG_ERROR';
export const ADD_LANG = 'ADD_LANG';
export const UPDATE_LANG = 'UPDATE_LANG';
export const DELETE_LANG = 'DELETE_LANG';


